# Generated by Django 5.0.6 on 2025-02-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_comment_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
